### ISSUE TITLE
`TypeError` upon `import napari_tools_menu` with version 0.1.18 (in the absence of QT bindings)

### ISSUE THREAD

**Issue by tcompa** [haesleinhuepf/napari-tools-menu#11]
Version 0.1.18 of napari-tools-menu (which includes #9 and #10) was meant to provide the possibility to import `napari_tools_menu` even in the absence of QT bindings, by only raising some warnings instead of errors. I now realize that we missed something in those PRs, and the import still fails with 0.1.18. Also, the failure is different from the previous version (this time it also comes from `napari/_qt/__init__.py`). 

In the following, I trigger the import error by:
1. Creating a fresh conda env (e.g. with python 3.9),
2. pip-installing napari-tools-menu==0.1.18,
3. trying to import napari-tools-menu from python.

Below I report the two errors obtained with versions 0.1.18 and 0.1.17, and they both result in
```
>>> napari_tools_menu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'napari_tools_menu' is not defined
```

Notice that in both cases (0.1.17 and 0.1.18) the napari version fetched by pip is the same (0.4.17). Trying a downgrade to 0.4.16 did not change anything in any of the two tests.

I will dig into this as soon as possible.

---

Import error with napari-tools-menu 0.1.18:
```
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari_tools_menu
Traceback (most recent call last):
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/qtpy/__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari/_qt/__init__.py", line 9, in <module>
    from qtpy import API_NAME, QtCore
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py", line 7, in <module>
    import napari._qt
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari/_qt/__init__.py", line 12, in <module>
    raise type(e)(
TypeError: __init__() takes 1 positional argument but 2 were given
```

---

Import error with napari-tools-menu 0.1.17:
```
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari_tools_menu
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:6: UserWarning: importing napari._qt failed
  warnings.warn("importing napari._qt failed")
Traceback (most recent call last):
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/qtpy/__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py", line 9, in <module>
    from qtpy.QtWidgets import QMenu
  File "/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
```

**Comment by tcompa** [comment]
It turns out that this is a qtpy=2.3.0 issue.

With napari-tools-menu=0.1.18 and qtpy=2.2.1 we get the expected behavior:
```
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari_tools_menu
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:10: UserWarning: Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.
  warnings.warn("Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.")
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:221: UserWarning: Error in monkey patching napari. Please let @haesleinleinhuepf know at
https://github.com/haesleinhuepf/napari-tools-menu/issues
  warnings.warn("Error in monkey patching napari. Please let @haesleinleinhuepf know at\nhttps://github.com
```

The diff between qtpy 2.2.1 and 2.30 is [here](https://github.com/spyder-ide/qtpy/compare/v2.2.1...v2.3.0), and the relevant PR seems to be [this one](https://github.com/spyder-ide/qtpy/pull/379/files). I think this is not a napari-tools-menu issue, I will follow up over there.

**Comment by tcompa** [comment]
Wonderful, thanks.
It does work as expected indeed:
```
$ pip show napari-tools-menu
Name: napari-tools-menu
Version: 0.1.19
Summary: Attaches a customizable Tools menu to napari
Home-page: https://github.com/haesleinhuepf/napari-tools-menu
Author: Robert Haase
Author-email: robert.haase@tu-dresden.de
License: BSD-3-Clause
Location: /home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages
Requires: napari, napari-plugin-engine, numpy
Required-by: 

$ pip show napari
Name: napari
Version: 0.4.17
Summary: n-dimensional array viewer in Python
Home-page: https://napari.org
Author: napari team
Author-email: napari-steering-council@googlegroups.com
License: BSD 3-Clause
Location: /home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages
Requires: app-model, appdirs, cachey, certifi, dask, imageio, jsonschema, magicgui, napari-console, napari-plugin-engine, napari-svg, npe2, numpy, numpydoc, pandas, Pillow, pint, psutil, psygnal, pydantic, pygments, PyOpenGL, PyYAML, qtpy, scikit-image, scipy, sphinx, superqt, tifffile, toolz, tqdm, typing-extensions, vispy, wrapt
Required-by: napari-tools-menu

$ pip show qtpy
Name: QtPy
Version: 2.3.0
Summary: Provides an abstraction layer on top of the various Qt bindings (PyQt5/6 and PySide2/6).
Home-page: https://github.com/spyder-ide/qtpy
Author: Colin Duquesnoy and the Spyder Development Team
Author-email: spyder.python@gmail.com
License: MIT
Location: /home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages
Requires: packaging
Required-by: magicgui, napari, napari-console, qtconsole, superqt

$ python
Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari_tools_menu
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:10: UserWarning: Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.
  warnings.warn("Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.")
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:221: UserWarning: Error in monkey patching napari. Please let @haesleinleinhuepf know at
https://github.com/haesleinhuepf/napari-tools-menu/issues
  warnings.warn("Error in monkey patching napari. Please let @haesleinleinhuepf know at\nhttps://github.com/haesleinhuepf/napari-tools-menu/issues")
>>> napari_tools_menu.__version__
'0.1.19'
```
