### ISSUE TITLE
WARNING: Could not load OpenGL library. UserWarning: Error in monkey patching napari.

### ISSUE THREAD

**Issue by adiezsanchez** [haesleinhuepf/napari-tools-menu#13]
Hi @haesleinhuepf , I was just testing a small pipeline I built using .cle and APOC in Windows Linux Subsystem, WSL (it works just fine on Windows but wanted to test if the filepaths were OS agnostic).

Anyways after generating the venv inside WSL using <code> mamba create -n napari-devbio devbio-napari python=3.9 pyqt -c conda-forge</code>, activating it and running my ppp_GUI.PY script (https://github.com/adiezsanchez/intestinal_organoid_brightfield_analysis) I got the following error message:

WARNING: Could not load OpenGL library.
/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari_tools_menu/__init__.py:10: UserWarning: Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.
  warnings.warn("Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.")
/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari_tools_menu/__init__.py:221: UserWarning: Error in monkey patching napari. Please let @haesleinleinhuepf know at
https://github.com/haesleinhuepf/napari-tools-menu/issues
  warnings.warn("Error in monkey patching napari. Please let @haesleinleinhuepf know at\nhttps://github.com/haesleinhuepf/napari-tools-menu/issues")
Traceback (most recent call last):
  File "/home/albertds/github_repos/intestinal_organoid_brightfield_analysis/ppp_GUI.py", line 6, in <module>
    from utils import (
  File "/home/albertds/github_repos/intestinal_organoid_brightfield_analysis/utils.py", line 7, in <module>
    import napari_segment_blobs_and_things_with_membranes as nsbatwm  # version 0.3.6
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari_segment_blobs_and_things_with_membranes/__init__.py", line 23, in <module>
    from napari_time_slicer import time_slicer
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari_time_slicer/__init__.py", line 4, in <module>
    from ._function import napari_experimental_provide_function
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari_time_slicer/_function.py", line 7, in <module>
    from napari.layers import Image, Labels, Layer
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/layers/__init__.py", line 9, in <module>
    from napari.layers.base import Layer
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/layers/base/__init__.py", line 1, in <module>
    from napari.layers.base._base_constants import ActionType
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/layers/base/_base_constants.py", line 4, in <module>
    from napari.utils.misc import StringEnum
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/utils/__init__.py", line 2, in <module>
    from napari.utils.colormaps import Colormap
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from napari.utils.colormaps.colormap import Colormap
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/utils/colormaps/colormap.py", line 7, in <module>
    from napari.utils.color import ColorArray
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/utils/color.py", line 7, in <module>
    from napari.utils.colormaps.standardize_color import transform_color
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/napari/utils/colormaps/standardize_color.py", line 27, in <module>
    from vispy.color import ColorArray, get_color_dict, get_color_names
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/vispy/color/__init__.py", line 12, in <module>
    from .colormap import (Colormap, BaseColormap,  # noqa
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/vispy/color/colormap.py", line 14, in <module>
    import vispy.gloo
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/vispy/gloo/__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/vispy/gloo/gl/__init__.py", line 230, in <module>
    from . import es2 as default_backend  # noqa
  File "/home/albertds/miniforge3/envs/napari-devbio/lib/python3.9/site-packages/vispy/gloo/gl/es2.py", line 48, in <module>
    raise OSError('GL ES 2.0 library not found')
OSError: GL ES 2.0 library not found

**Comment by haesleinhuepf** [comment]
Hi @adiezsanchez ,

the OpenGL error hints to a problem with the napari viewer. It cannot diplay the image because of a missing driver. Unfortunately, I have no experience with this. Related / similar discussions
* https://askubuntu.com/questions/1223921/cairo-can-not-find-opengl-es-2-0-headers-on-ubuntu-18-04
* https://stackoverflow.com/questions/25114792/how-can-i-import-opengl-in-anaconda-python
* https://forum.image.sc/t/conda-forge-recipe-with-napari-dependency/83903
* https://forum.image.sc/t/napari-issues-on-bigsur/52630

If one of those helps, please notify us here. Thanks!

Best,
Robert
